// app/privacy-policy/page.tsx
import { Metadata } from 'next'
import Link from 'next/link'
import { Navbar } from '@/components/navbar'
import { Footer } from '@/components/footer'

export const metadata: Metadata = {
  title: 'Privacy Policy | iz4ru.byte',
  description: 'Privacy Policy for iz4ru.byte - Last updated April 25, 2026',
}

export default function PrivacyPolicyPage() {
  return (
    <div className="min-h-screen flex flex-col">
      <Navbar />
      
      <main className="flex-1 w-full py-16">
        <article className="max-w-4xl mx-auto px-8 sm:px-8 prose prose-neutral dark:prose-invert">
          
          {/* Header */}
          <div className="mb-12 pb-8 border-b border-border">
            <h1 className="font-lora text-4xl sm:text-5xl font-bold text-foreground mb-4">
              Privacy Policy
            </h1>
            <p className="text-muted-foreground text-lg">
              Last updated: <time dateTime="2026-04-25">April 25, 2026</time>
            </p>
          </div>

          {/* Introduction */}
          <div className="prose-custom space-y-6">
            <p className="text-foreground/85 leading-relaxed">
              This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
            </p>
            <p className="text-foreground/85 leading-relaxed">
              We use Your Personal Data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
            </p>
          </div>

          {/* Interpretation and Definitions */}
          <section className="mt-12 space-y-6">
            <h2 className="font-lora text-3xl font-bold text-foreground mt-10 mb-4">
              Interpretation and Definitions
            </h2>
            
            <h3 className="font-lora text-2xl font-semibold text-foreground mt-8 mb-3">
              Interpretation
            </h3>
            <p className="text-foreground/85 leading-relaxed">
              The words whose initial letters are capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
            </p>

            <h3 className="font-lora text-2xl font-semibold text-foreground mt-8 mb-3">
              Definitions
            </h3>
            <p className="text-foreground/85 leading-relaxed mb-4">
              For the purposes of this Privacy Policy:
            </p>
            <ul className="space-y-3 text-foreground/85 list-disc pl-6">
              <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
              <li><strong>Affiliate</strong> means an entity that controls, is controlled by, or is under common control with a party, where &quot;control&quot; means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
              <li><strong>Company</strong> (referred to as either &quot;the Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in this Privacy Policy) refers to <strong>iz4ru.byte</strong>.</li>
              <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
              <li><strong>Country</strong> refers to: <strong>Indonesia</strong></li>
              <li><strong>Device</strong> means any device that can access the Service such as a computer, a cell phone or a digital tablet.</li>
              <li><strong>Personal Data</strong> (or &quot;Personal Information&quot;) is any information that relates to an identified or identifiable individual.</li>
              <li><strong>Service</strong> refers to the Website.</li>
              <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company.</li>
              <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</li>
              <li><strong>Website</strong> refers to <strong>iz4ru.byte</strong>, accessible from <Link href="/" className="text-primary hover:underline">https://iz4ru-byte.vercel.app/</Link>.</li>
              <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
            </ul>
          </section>

          {/* Collecting and Using Your Personal Data */}
          <section className="mt-12 space-y-6">
            <h2 className="font-lora text-3xl font-bold text-foreground mt-10 mb-4">
              Collecting and Using Your Personal Data
            </h2>

            <h3 className="font-lora text-2xl font-semibold text-foreground mt-8 mb-3">
              Types of Data Collected
            </h3>

            <h4 className="font-lora text-xl font-semibold text-foreground mt-6 mb-3">
              Personal Data
            </h4>
            <p className="text-foreground/85 leading-relaxed mb-3">
              While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
            </p>
            <ul className="list-disc pl-6 space-y-2 text-foreground/85">
              <li>Email address</li>
              <li>First name and last name</li>
            </ul>

            <h4 className="font-lora text-xl font-semibold text-foreground mt-6 mb-3">
              Usage Data
            </h4>
            <p className="text-foreground/85 leading-relaxed">
              Usage Data is collected automatically when using the Service. Usage Data may include information such as Your Device&apos;s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
            </p>

            <h4 className="font-lora text-xl font-semibold text-foreground mt-6 mb-3">
              Tracking Technologies and Cookies
            </h4>
            <p className="text-foreground/85 leading-relaxed">
              We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies We use include beacons, tags, and scripts to collect and track information and to improve and analyze Our Service.
            </p>
            <p className="text-foreground/85 leading-relaxed mt-3">
              We use both Session and Persistent Cookies for the purposes set out below including Necessary/Essential Cookies, Functionality Cookies, and Cookies Policy Acceptance Cookies.
            </p>

            <h3 className="font-lora text-2xl font-semibold text-foreground mt-8 mb-3">
              Use of Your Personal Data
            </h3>
            <p className="text-foreground/85 leading-relaxed mb-3">
              The Company may use Personal Data for the following purposes:
            </p>
            <ul className="space-y-3 text-foreground/85 list-disc pl-6">
              <li><strong>To provide and maintain our Service</strong>, including to monitor the usage of our Service.</li>
              <li><strong>To manage Your Account:</strong> to manage Your registration as a user of the Service.</li>
              <li><strong>For the performance of a contract:</strong> the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased.</li>
              <li><strong>To contact You:</strong> To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication.</li>
              <li><strong>To provide You</strong> with news, special offers, and general information about other goods, services and events which We offer.</li>
              <li><strong>To manage Your requests:</strong> To attend and manage Your requests to Us.</li>
              <li><strong>For business transfers:</strong> We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets.</li>
              <li><strong>For other purposes:</strong> We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve Our Service.</li>
            </ul>

            <h3 className="font-lora text-2xl font-semibold text-foreground mt-8 mb-3">
              Retention of Your Personal Data
            </h3>
            <p className="text-foreground/85 leading-relaxed">
              The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations, resolve disputes, and enforce our legal agreements and policies.
            </p>
            <p className="text-foreground/85 leading-relaxed mt-3">
              <strong>Retention Periods:</strong> Account Information is retained for the duration of your account relationship plus up to <strong>24 months</strong> after account closure. Usage Data and analytics data are retained for up to <strong>24 months</strong> from the date of collection.
            </p>

            <h3 className="font-lora text-2xl font-semibold text-foreground mt-8 mb-3">
              Transfer of Your Personal Data
            </h3>
            <p className="text-foreground/85 leading-relaxed">
              Your information, including Personal Data, is processed at the Company&apos;s operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction.
            </p>

            <h3 className="font-lora text-2xl font-semibold text-foreground mt-8 mb-3">
              Delete Your Personal Data
            </h3>
            <p className="text-foreground/85 leading-relaxed">
              You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You. You may update, amend, or delete Your information at any time by signing in to Your Account, if you have one, and visiting the account settings section. You may also contact Us to request access to, correct, or delete any Personal Data that You have provided to Us.
            </p>

            <h3 className="font-lora text-2xl font-semibold text-foreground mt-8 mb-3">
              Security of Your Personal Data
            </h3>
            <p className="text-foreground/85 leading-relaxed">
              The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially reasonable means to protect Your Personal Data, We cannot guarantee its absolute security.
            </p>
          </section>

          {/* Children's Privacy */}
          <section className="mt-12 space-y-6">
            <h2 className="font-lora text-3xl font-bold text-foreground mt-10 mb-4">
              Children&apos;s Privacy
            </h2>
            <p className="text-foreground/85 leading-relaxed">
              Our Service does not address anyone under the age of <strong>16</strong>. We do not knowingly collect personally identifiable information from anyone under the age of 16. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us.
            </p>
          </section>

          {/* Links to Other Websites */}
          <section className="mt-12 space-y-6">
            <h2 className="font-lora text-3xl font-bold text-foreground mt-10 mb-4">
              Links to Other Websites
            </h2>
            <p className="text-foreground/85 leading-relaxed">
              Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party&apos;s site. We strongly advise You to review the Privacy Policy of every site You visit.
            </p>
          </section>

          {/* Changes to this Privacy Policy */}
          <section className="mt-12 space-y-6">
            <h2 className="font-lora text-3xl font-bold text-foreground mt-10 mb-4">
              Changes to this Privacy Policy
            </h2>
            <p className="text-foreground/85 leading-relaxed">
              We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page and updating the &quot;Last updated&quot; date at the top of this Privacy Policy.
            </p>
          </section>

          {/* Contact Us */}
          <section className="mt-12 mb-16 p-6 bg-secondary/30 rounded-xl border border-border">
            <h2 className="font-lora text-3xl font-bold text-foreground mb-4">
              Contact Us
            </h2>

            <p className="text-foreground/85 leading-relaxed mb-4">
              If you have any questions about this Privacy Policy, You can contact us:
            </p>

            <ul className="space-y-2 text-foreground/85">
              <li>
                <strong>By email:</strong>{' '}
                <a
                  href="mailto:satriamaulanaridwan56@gmail.com"
                  className="text-primary hover:underline break-all block"
                >
                  satriamaulanaridwan56@gmail.com
                </a>
              </li>

              <li>
                <strong>By visiting this page:</strong>{' '}
                <Link
                  href="/"
                  className="text-primary hover:underline break-all block"
                >
                  https://iz4ru-byte.vercel.app/
                </Link>
              </li>
            </ul>
          </section>

        </article>
      </main>

      <Footer />
    </div>
  )
}